import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

export const THEME = {
  light: {
    background: '#FFF6EE',
    foreground: '#1F1714',
    card: '#FFF6EE',
    cardForeground: '#1F1714',
    popover: '#FFF6EE',
    popoverForeground: '#1F1714',
    primary: '#C75A3A',
    primaryForeground: '#FFF6EE',
    secondary: '#A94E2C',
    secondaryForeground: '#FFF6EE',
    muted: '#E8D6C8',
    mutedForeground: '#A94E2C',
    accent: '#F4B860',
    accentForeground: '#1F1714',
    destructive: '#C75A3A',
    border: '#E8D6C8',
    input: '#E8D6C8',
    ring: '#C75A3A',
    radius: '0.625rem',
    chart1: '#C75A3A',
    chart2: '#A94E2C',
    chart3: '#F4B860',
    chart4: '#E8D6C8',
    chart5: '#1F1714',
  },
  dark: {
    background: '#1F1714',
    foreground: '#FFF6EE',
    card: '#2B201C',
    cardForeground: '#FFF6EE',
    popover: '#2B201C',
    popoverForeground: '#FFF6EE',
    primary: '#F4B860',
    primaryForeground: '#1F1714',
    secondary: '#C75A3A',
    secondaryForeground: '#FFF6EE',
    muted: '#4A332A',
    mutedForeground: '#E8D6C8',
    accent: '#F4B860',
    accentForeground: '#1F1714',
    destructive: '#C75A3A',
    border: '#4A332A',
    input: '#4A332A',
    ring: '#F4B860',
    radius: '0.625rem',
    chart1: '#F4B860',
    chart2: '#C75A3A',
    chart3: '#A94E2C',
    chart4: '#E8D6C8',
    chart5: '#FFF6EE',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
